name: "On Push Action"

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: "Run test"
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: "Displays Xcode current version"
        run: sudo xcode-select -p

      - name: Setup Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Run lint, build and test application
        run: bundle exec fastlane check_code_quality
        env:
          FL_SWIFTLINT_STRICT: ${{ vars.FL_SWIFTLINT_STRICT }}
          FL_SWIFTLINT_IGNORE_EXIT_STATUS: ${{ vars.FL_SWIFTLINT_IGNORE_EXIT_STATUS }}
          FL_SWIFTLINT_RAISE_IF_SWIFTLINT_ERROR: ${{ vars.FL_SWIFTLINT_RAISE_IF_SWIFTLINT_ERROR }}
          SLACK_URL: ${{ secrets.SLACK_URL }}